### ISSUE TITLE
Fix required versions - poison is unresolvable

### ISSUE THREAD

**Issue by montebrown** [peburrows/goth#39]
goth depends on:
 - poison 2.1 or 3.0
 - json_web_token

json_web_token depends on:
 - poison 3.1

This makes the dependency graph unresolvable. The workaround is to set "override: true" for the poison version.

**Comment by peburrows** [comment]
Yeah, looks like things have changed since the last time I released a version. I'll work on the dependency specs to fix this.

**Comment by peburrows** [comment]
So, I started looking into this, and the current version requirements shouldn't be an issue. Specifying `~> 3.0` essentially resolves to `>= 3.0 and < 4.0`, and it works just fine with `3.1` for me.

Please let me know if you're seeing an actual error, and if so, what that error might be. Otherwise, I'm going to consider this issue closed.

**Comment by munjalpatel** [comment]
I am also running into this issue. I am not able to do `mix deps.get`
